# **Numpy Assignment**

In [2]:
import numpy as np

Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [ ]:
#creating a 3x3 NumPy array with random integers between 1 and 100

arr = np.random.randint(1,100,(3,3))
arr

array([[69, 89, 99],
       [71, 81, 16],
       [ 2, 63, 40]])

In [ ]:
#using transpose to interchange its rows and columns

arr.T

array([[69, 71,  2],
       [89, 81, 63],
       [99, 16, 40]])

Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [ ]:
#generating a 1D array with 10 elements
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1.ndim    #provides dimension

1

In [ ]:
arr1.shape   #provides shape

(10,)

In [ ]:
arr1.size    #provides the no. of elements

10

In [ ]:
#reshaping the arr1 in 2*5 array
arr2 = np.reshape(arr1,(2,5))
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr2.size    #there is no change in the no.of elements

10

In [ ]:
#again reshaping arr2 in 5*2 array
arr3 = np.reshape(arr2,(5,2))
arr3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
arr3.size      #there is no change in the no.of elements

10

Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [ ]:
#Create a 4x4 array with random float values
arr = np.random.rand(4,4)
arr

array([[0.53565587, 0.53128243, 0.4342998 , 0.12965028],
       [0.95467916, 0.89986355, 0.6942032 , 0.35541494],
       [0.44146134, 0.80432394, 0.97415502, 0.92319287],
       [0.52596061, 0.19713713, 0.60749823, 0.32077983]])

In [ ]:
#add a border of zeros around the array

bordered_arr = np.pad(arr,pad_width = 1,mode= 'constant',constant_values=0)
bordered_arr

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.53565587, 0.53128243, 0.4342998 , 0.12965028,
        0.        ],
       [0.        , 0.95467916, 0.89986355, 0.6942032 , 0.35541494,
        0.        ],
       [0.        , 0.44146134, 0.80432394, 0.97415502, 0.92319287,
        0.        ],
       [0.        , 0.52596061, 0.19713713, 0.60749823, 0.32077983,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [ ]:
import numpy as np
arr = np.arange(10,61,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [ ]:
#areating an array
string = np.array( ['python', 'numpy', 'pandas'])
string

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
#transforming array of strings into uppercase
np.char.upper(string)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [ ]:
#capitalizing each letter of the array string
np.char.capitalize(string)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [ ]:
#swaping the case of each letter of the array string
np.char.swapcase(string)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [ ]:
#splitting each word of the array string
np.char.split(string)

array([list(['python']), list(['numpy']), list(['pandas'])], dtype=object)

Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [ ]:
#create a numpy array of words
word_arr = np.array(['Kirti','Gupta'])
word_arr

array(['Kirti', 'Gupta'], dtype='<U5')

In [ ]:
#inserting space between each character of every word in the given array
space_word_arr = np.array([[' '.join(word) for word in row] for row in word_arr])
space_word_arr

array([['K', 'i', 'r', 't', 'i'],
       ['G', 'u', 'p', 't', 'a']], dtype='<U1')

Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [ ]:
arr1 = np.random.randint(1,5,(4,4))
arr1

array([[2, 1, 3, 2],
       [2, 2, 3, 2],
       [1, 2, 2, 1],
       [1, 4, 3, 2]])

In [ ]:
arr2 = np.random.randint(6,9,(4,4))
arr2

array([[7, 8, 7, 6],
       [6, 6, 8, 6],
       [8, 8, 8, 8],
       [6, 8, 7, 7]])

In [ ]:
#element-wise addition
arr1 + arr2

array([[ 9,  9, 10,  8],
       [ 8,  8, 11,  8],
       [ 9, 10, 10,  9],
       [ 7, 12, 10,  9]])

In [ ]:
#element-wise subtraction
arr1 - arr2

array([[-5, -7, -4, -4],
       [-4, -4, -5, -4],
       [-7, -6, -6, -7],
       [-5, -4, -4, -5]])

In [ ]:
#element-wise multiplication
arr1 * arr2

array([[14,  8, 21, 12],
       [12, 12, 24, 12],
       [ 8, 16, 16,  8],
       [ 6, 32, 21, 14]])

In [ ]:
#element-wise division
arr1/arr2

array([[0.28571429, 0.125     , 0.42857143, 0.33333333],
       [0.33333333, 0.33333333, 0.375     , 0.33333333],
       [0.125     , 0.25      , 0.25      , 0.125     ],
       [0.16666667, 0.5       , 0.42857143, 0.28571429]])

Q8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [ ]:
#creating a 5x5 identity matrix

matrix = np.eye(5,dtype=int)
matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
#extracting diagonal elements
matrix[0][0]

1

In [ ]:
matrix[1][1]

1

In [ ]:
matrix[2][2]

1

In [ ]:
matrix[3][3]

1

In [ ]:
matrix[4][4]

1

Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [4]:
#checking prime no.
def is_prime(n):
  if n<=1:
    return False
  for i in range(2,int(n**0.5)+1):
    if n%i==0:
      return False
  return True

#generating a numpy array of 100 integers between 0 and 1000
num_arr = np.random.randint(0,1001,size=100)
num_arr

array([921, 680, 597, 810, 930, 415, 988, 743, 425, 109, 127, 696, 852,
        49, 367, 130, 357, 575, 386, 284,  26, 303, 433, 733, 762, 191,
        35, 543, 571, 615, 994, 731, 611, 139, 722, 780, 512, 175, 113,
       987, 515, 133, 525, 411, 308, 474, 302, 354, 965, 931, 491, 286,
       926, 661, 279, 914, 622, 498, 882, 180, 872, 128, 868, 235, 856,
       783,  20,   3, 664, 857, 221, 524, 930, 507, 536,  43, 829, 936,
       334, 320, 766, 487, 130, 565,   6, 128, 692,  41,  44, 540,  78,
         8,   2, 191, 829, 645, 239, 126, 922, 790])

In [6]:
#finding all the prime no's in the given array using list comprehension

prime_no = [num for num in num_arr if is_prime(num)]
print('Prime numbers:' , prime_no)

Prime numbers: [743, 109, 127, 367, 433, 733, 191, 571, 139, 113, 491, 661, 3, 857, 43, 829, 487, 41, 2, 191, 829, 239]


Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [16]:
#creating a numpy array representing daily temperatures for a month
np.random.seed(0)    #seed is used for reproducibility
daily_temp = np.random.randint(10,36,size=30)
daily_temp

array([22, 25, 31, 10, 13, 13, 17, 19, 29, 31, 28, 14, 33, 16, 34, 34, 22,
       11, 16, 17, 33, 24, 34, 27, 15, 35, 23, 18, 19, 30])

In [17]:
#reshaping the array to have 4 weeks
weeks = daily_temp[:28]
weeks

array([22, 25, 31, 10, 13, 13, 17, 19, 29, 31, 28, 14, 33, 16, 34, 34, 22,
       11, 16, 17, 33, 24, 34, 27, 15, 35, 23, 18])

In [10]:
weeks.size

28

In [18]:
w1 = weeks.reshape(4,7)
w1

array([[22, 25, 31, 10, 13, 13, 17],
       [19, 29, 31, 28, 14, 33, 16],
       [34, 34, 22, 11, 16, 17, 33],
       [24, 34, 27, 15, 35, 23, 18]])

In [19]:
remaining_days = daily_temp[28:]
remaining_days

array([19, 30])

In [24]:
#calculating average
weekly_avg = np.average(w1, axis=1)
remaining_days_avg = np.average(remaining_days)
total_weekly_avg = np.append(weekly_avg,remaining_days_avg)
total_weekly_avg

array([18.71428571, 24.28571429, 23.85714286, 25.14285714, 24.5       ])

#**Assignment Completed**